# Generated by Django 4.0.4 on 2022-05-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.location')),
            ],
        ),
    ]
